name: CI

on:
  push:
    branches:
      - v6

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Cache asdf
        id: cache-asdf
        uses: actions/cache@v4
        with:
          path: ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-

      - name: Cache pnpm
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - if: ${{ steps.cache-asdf.outputs.cache-hit != 'true' }}
        name: Setup pnpm
        run: |
          corepack enable
          asdf reshim

      - name: Install modules
        run: pnpm install --frozen-lockfile
      - name: Lint Typecheck Test Build
        run: pnpm run ci
